import './globals.css'
import localFont from 'next/font/local'
import { Inter } from 'next/font/google'
import { getGlobals, getMenuByLocation } from '@/libs/wordpress'
import Header from '@/app/components/globals/header'
import Theme from '@/app/components/globals/theme'
import Footer from '@/app/components/globals/footer'
import { getMediaById } from '@/libs/wordpress'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const strawfond = localFont({
	src: [
		{
			path: '../../public/strawford/Strawford-Regular.otf',
			weight: '400',
			style: 'normal',
		},
		{
			path: '../../public/strawford/Strawford-Medium.otf',
			weight: '500',
			style: 'medium',
		},
	],
	variable: '--strawford',
})

export default async function RootLayout({ children }) {
	const { header, themeVars = null, footer = null } = await getGlobals()
	const menuHeader = await getMenuByLocation('main_menu')
	const logoImage = await getMediaById(header.logo)

	return (
		<html lang="en" className="bg-background">
			<body className={`${strawfond.variable} ${strawfond.className} isolate`}>
				<Theme variables={themeVars} />
				<Header menu={menuHeader} logo={logoImage} />
				{children}
				{/* {footer ?? <Footer {...footer} />} */}
			</body>
		</html>
	)
}
