import './globals.css'
import localFont from 'next/font/local'
import { Inter } from 'next/font/google'
import { getGlobals } from '@/libs/wordpress'
import Header from '@/components/globals/header'
import Theme from '@/components/globals/theme'
import Footer from '@/components/globals/footer'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const strawfond = localFont({
	src: [
		{
			path: '../../public/strawford/Strawford-Regular.otf',
			weight: '400',
			style: 'normal',
		},
		{
			path: '../../public/strawford/Strawford-Medium.otf',
			weight: '500',
			style: 'medium',
		},
	],
	variable: '--strawford',
})

export default async function RootLayout({ children }) {
	const { header, themeVars, footer } = await getGlobals()
	return (
		<html lang="en" className="bg-background">
			<body className={`${strawfond.variable} ${strawfond.className} isolate`}>
				<Theme variables={themeVars} />
				<Header {...header} />
				{children}
				<Footer {...footer} />
			</body>
		</html>
	)
}
